<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All selected models must have same source state.' => 'Wszystkie modele muszą mieć ten sam stan początkowy.',
    'Cancel' => 'Anuluj',
    'Change status from {source} to {target}' => 'Zmiana statusu z {source} do {target}',
    'Failed to save changes.' => 'Nie udało się zapisać zmian.',
    'Model {model} needs to implement the IStateful interface.' => 'Model {model} musi implementować interfejs IStateful.',
    'Reason' => 'Powód',
    'State change' => 'Zmiana stanu',
    'Status has already been changed' => 'Status został zmieniony',
    'You cannot change state from {from} to {to} because such state transition is not allowed.' => 'Nie możesz zmienić stanu z {from} na {to} ponieważ taka zmiana nie jest dozwolona',
    'You cannot change state from {from} to {to} because such state transition is undefined.' => 'Nie możesz zmienić stanu z {from} na {to} ponieważ taka zmiana stanu nie została zdefiniowana.',
    'return to' => 'powrót do',
    '{number} out of {total} {model} has been successfully updated.' => '{number} na {total} {model} zostało zaktualizowane.',
];
